### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UntitledProject4Content)
add_subdirectory(UntitledProject4)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProject4Contentplugin
    UntitledProject4plugin)